services:
  adguard-home:
    user: "0:0"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
    networks:
      dockervlan:
        ipv4_address: 172.20.0.130
    mac_address: ""

  uptime-kuma:
    environment:
      UPTIME_KUMA_HOST: 172.20.0.132
    networks:
      dockervlan:
        ipv4_address: 172.20.0.132
    mac_address: ""

  node-red:
    networks:
      dockervlan:
        ipv4_address: 172.20.0.131
    mac_address: ""

  test:
    networks:
      dockervlan:
        ipv4_address: 172.20.0.133

networks:
  dockervlan:
    driver: bridge
    driver_opts:
      parent: ""
    ipam:
      config:
        - subnet: 172.20.0.0/24
