name: "Repository CI"

'on':
  # run on pushes to main
  push:
    branches:
      - main
      - gh-readonly-queue/main/**
  # run on pull requests that target the main branch
  pull_request:
    branches:
      - main
  # run on pull request events
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
      - reopened
      # - review_requested
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  repository:
    permissions:
      contents: read
    # Only run for the repository owner or on non-pull_request_target events
    # to protect secrets
    if: >
      github.event_name != 'pull_request_target' ||
      github.event.pull_request.head.repo.full_name == github.repository
    uses: busybeaver/homelab-shared/.github/workflows/repository.yaml@e5bc968880ee2f22fb8b5f4b7191777cebc5fb2c
    # v1.1.95
    secrets:
      REPOSITORY_ASSISTANT_APP_ID: ${{ secrets.REPOSITORY_ASSISTANT_APP_ID }}
      REPOSITORY_ASSISTANT_PRIVATE_KEY: ${{ secrets.REPOSITORY_ASSISTANT_PRIVATE_KEY }}
